networks:
  my-network:
    driver: bridge

volumes:
    redis-data:
        driver: local

services:
    redis:
        image: redislabs/redismod
        container_name: redis
        volumes:
            - redis-data:/data
        ports:
            - '6379:6379'
        networks:
            - my-network
    web:
        build: .
        image: crypto-server:latest
        container_name: web
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks:
            - my-network
        environment:
            - API_KEY=A0398331-92F1-4747-B9CC-73E5B7E423FE
            - MINUTES_TO_LIVE=5
            - PORT_NUMBER=5000
            - DEFAULT_CRYPTO=BTC
            - API_ADDRESS=https://rest.coinapi.io/v1/assets/
